### ISSUE TITLE
Forge crash when writing containers to short buffers

### ISSUE THREAD

**Issue by x42** [drobilla/lv2#27]
When writing data to a lv2 atom port, forge.h does no correctly check available port-buffer-size, leading so to segfaults.

a potential fix is to change forge.h
```diff
@@ -298,6 +298,6 @@
 	} else {
 		out = (LV2_Atom_Forge_Ref)forge->buf + forge->offset;
 		uint8_t* mem = forge->buf + forge->offset;
-		if (forge->offset + size > forge->size) {
+		if (forge->offset + size >= forge->size) {
 			return 0;
 		}
 		forge->offset += size;
```

This was found by re-using an atom-port, writing to it twice.

 if the first write is an empty sequence, the "capacity" is 8 bytes. Trying to write a new sequence segfauls in lv2_atom_forge_raw.

see also https://github.com/sadko4u/lsp-plugins/issues/28#issuecomment-462171971
example code to reproduce: https://gist.github.com/x42/b82769d2b3567b0a5c77c2bd857326ae

**Comment by drobilla** [comment]
37e64e9

**Comment by x42** [comment]
Those tests don't seem to catch overflows in `lv2_atom_forge_raw()`. e.g. when the buffer is too small to even write a sequence-head or frame_time.

This can happen e.g. in Ardour when a Plugin has an Atom output that is used for both MIDI and GUI. When the port is unused, Ardour provides a scratch-buffer and that may be overwritten.

2nd time around `(LV2_Atom_Sequence*) port)->atom.size` is 8 [bytes] (just the size of the seq-head),  yet to write that again fails. See the linked gist.

**Comment by drobilla** [comment]
They do, it attempts to write a literal to a buffer with 1 byte.

I don't understand what you mean with this "second time around" stuff.  It sounds like the linked example snippet, where you are using the size of a written atom as the capacity to write to it again.  That's wrong, not a forge bug.  You will get crashes, because you are telling the forge there is more space available than there actually is.

Ardour is required to initialize any atom passed to a plugin as an output correctly, as a Chunk with size set to the correct capacity.  You can not do this again once the plugin has been called without resetting the buffer, and the plugin can not forge to it once then use the same init code again because the capacity is lost.

If you want to rewrite an atom output in a plugin for some reason (you shouldn't), you need to store the original capacity somewhere.  Using the initial size as a capacity like this is a bit janky, but it seemed better than a different wrapper type in the buffer since you can point plugins directly at any atom, as with audio.

**Comment by drobilla** [comment]
Ah, I see now.  I was confused by the title and suggested fix.  This was actually an issue with pushing containers like sequences to the forge, then continuing to write even if it overflowed.  The frame in the forge pointed to NULL which would result in an eventual crash somewhere (further writing or popping).

c0a3fc6 fixes this and adds tests that I think cover all these cases.

**Comment by x42** [comment]
Thanks!
